version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.13"
    rust: "1.82"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs
