[package]
name = "ferrmion"
version = "0.5.4"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ferrmion"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
ndarray = {version="0.16.1", features=["rayon"]}
log = {version ="0.4", features = ["release_max_level_info"]}
ahash = "0.8.12"
permutation_iterator = "0.1.2"
rand = "0.9.2"
rand_xoshiro = "0.7.0"
argmin = "0.10.0"
argmin-observer-slog = "0.1.0"
num-complex = "0.4.6"
tinyvec = "1.10.0"
thiserror = "2.0.17"
arrow = { version = "56.2.0" }
pyo3-arrow = "0.15.0"
pyo3-log = "0.13.2"
pyo3 = "0.27.2"
numpy = "0.27.1"

[dev-dependencies]
proptest = "1.9.0"

[profile.profiling]
inherits = "release"
debug = true
