[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "ferrmion"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "deap>=1.4.3",
    "myst-sphinx-gallery>=0.3.0",
    "numpy>=1.24.4",
    "openfermion>=0.11.0",
    "pydantic>=2.10.6",
    "qiskit>=2.0.2",
    "qiskit-nature>=0.7.2",
    "rustworkx>=0.16.0",
]

[tool.maturin]
module-name = "ferrmion.core"
python-source = "python/"
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pre-commit>=3.5.0",
    "pytest>=8.3.5",
    "pytest-benchmark>=4.0.0",
    "pytest-cov>=6.1.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.12.11",
]
docs = [
    "myst-parser>=4.0.1",
    "sphinx>=7.1.2",
    "sphinx-rtd-theme>=3.0.2",
    "ffsim>=0.0.56",
    "qiskit>=2.0.2",
    "myst-nb>=1.2.0",
    "pydata-sphinx-theme>=0.16.1",
]

[tool.ruff]
exclude = ["docs/", "python/tests/", "python/ferrmion/__init__.py"]
line-length = 88
indent-width = 4

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
select = [
    "E4", "E7", "E9",
    "F",
    "D", #pydocstyle (lets add this when we actually write docstrings)
    "I", #isort
]
ignore = ["E741"]
