[package]
name = "ferrmion-python"
version = "0.7.3"
edition = "2021"

[lib]
name = "ferrmion"
crate-type = ["cdylib"]

[dependencies]
ferrmion-core = { path = "../ferrmion-core" }
pyo3 = { version = "0.24.0", features = ["num-complex"] }
numpy = "0.24.0"
pyo3-log = "0.12.4"
log = { version = "0.4", features = ["release_max_level_info"] }
ndarray = "0.16.1"
num-complex = "0.4.6"
tinyvec = "1.10.0"
