name: PR CICD
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to test?'
        required: true
jobs:
  pr:
    uses: ./.github/workflows/build.yaml
